plugins { id 'com.android.application' }

android { namespace 'com.example.qqprivatenotify'; compileSdk 35
    defaultConfig { applicationId 'com.example.qqprivatenotify'; minSdk 26; targetSdk 35; versionCode 32; versionName '1.2' }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:101.0.1'
    testImplementation 'junit:junit:4.13.2'
}
